
jobs:      
- job: OMF_APIJava

  pool:
    vmImage: 'Ubuntu-16.04'
  steps :

    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
        secureFile: config.properties

    # Copy Files
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: config.properties 
        targetFolder: '$(Build.SourcesDirectory)/basic_samples/OMF_API/Java/omfapijava/'
        #cleanTargetFolder: false # Optional
        overWrite: true # Optional
        #flattenFolders: false # Optional
      displayName: copy file
      
    - task: Maven@3
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/basic_samples/OMF_API/Java/omfapijava/pom.xml'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'test'
 