# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


  
jobs:      


- job: OMF_APIJava

  pool:
    name: 00-OSIManaged-Test
    demands: USERNAME -equals IAC8188$
  steps :

    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
        secureFile: prod_onprem_omf_config.properties

    # Copy Files
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents: prod_onprem_omf_config.properties
        targetFolder: '$(Build.SourcesDirectory)/basic_samples/OMF_API/Java/omfapijava/'
        #cleanTargetFolder: false # Optional
        overWrite: true # Optional
        #flattenFolders: false # Optional
      displayName: copy file      

    - script: |
        del config.properties
      workingDirectory:  '$(Build.SourcesDirectory)/basic_samples/OMF_API/Java/omfapijava/'
      displayName: 'del config file1'


    - script: |
        rename prod_onprem_omf_config.properties config.properties
      workingDirectory: '$(Build.SourcesDirectory)/basic_samples/OMF_API/Java/omfapijava/'
      displayName: 'rename config file'    
      
    - script: |
        mvn test
      workingDirectory: '$(Build.SourcesDirectory)/basic_samples/OMF_API/Java/omfapijava/'
      displayName: 'Run Test'
 
