trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OMF_API/Java'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OMF_API/Java'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/OMF_API/Java/omfapijava'
  - name: testPath
    value: '/basic_samples/OMF_API/Java/omfapijava'
  - name: CredFile
    value: config.properties
  - name: CredFileLibrary
    value: product-readiness.omf_api_java.ocs.properties
  - name: CredFileLibraryOP
    value: product-readiness.omf_api_java.onprem.properties
  - name: analysisProject
    value: OMF_API_Java

jobs:
  - job: Tests_OCS
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)$(projPath)/pom.xml'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'test'
        displayName: 'Run tests'

  - job: Tests_OnPrem
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryOP)
          filePath: $(projPath)

      - script: |
          mvn test
        workingDirectory: '$(Build.SourcesDirectory)$(testPath)'
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: java
