variables:
- group: LocalServer
- name: projpath
  value: /basic_samples/OMF_API/Java/omfapijava
- name: CredFile
  value: config.properties
- name: CredFileLibrary
  value: prod_onprem_omf_config.properties
- name: testpath
  value: /basic_samples/OMF_API/Java/omfapijava

  
jobs:      


- job: OMF_APIJava

  pool:
    name: 00-OSIManaged-Test
    demands: USERNAME -equals $(LocalServer)
  steps :

    # Download Secure File
    # Download a secure file to a temporary location on the build or release agent
    - task: DownloadSecureFile@1
      inputs:
        secureFile: $(CredFileLibrary)

    # Copy Files
    # Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths))
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents:  $(CredFileLibrary)
        targetFolder: '$(Build.SourcesDirectory)$(projpath)'
        #cleanTargetFolder: false # Optional  
        overWrite: true # Optional
        #flattenFolders: false # Optional 
      displayName: copy file

    - script: |
        del $(CredFile)
      workingDirectory:  '$(Build.SourcesDirectory)$(projpath)'
      displayName: 'rename config file1'


    - script: |
        rename  $(CredFileLibrary)  $(CredFile)
      workingDirectory: $(Build.SourcesDirectory)$(projpath)
      displayName: 'rename config file'     
      
    - script: |
        mvn test
      workingDirectory: $(Build.SourcesDirectory)$(testpath)
      displayName: 'Run Test'
 
