trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OMF_API/Python3'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OMF_API/Python3'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/OMF_API/Python3'
  - name: testPath
    value: '/basic_samples/OMF_API/Python3'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.omf_api_python.ocs.ini
  - name: CredFileLibraryOP
    value: product-readiness.omf_api_python.onprem.ini
  - name: covStream
    value: OMF_APIPy

jobs:
  - job: Tests_OCS
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'

      - script: |
          pip install setuptools wheel
          pip install unittest-xml-reporting    
          pip install pytest
          pip install pytest-cov
        displayName: 'Install tools'

      - script: |
          pip install -r requirements.txt
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Install requirements'

      - script: |
          python -m pytest ./program.py
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Run tests'

  - job: Tests_OnPrem
    pool:
      name: 00-OSIManaged-Test
      demands: USERNAME -equals $(covAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibraryOP)
          filePath: $(projPath)

      - script: |
          "C:\Program Files (x86)\Python37-32\Scripts\pip.exe" install -r requirements.txt
        workingDirectory: '$(Build.SourcesDirectory)$(projPath)'
        displayName: 'Install requirements'

      - script: |
          "C:\Program Files (x86)\Python37-32\python.exe" ./test.py
        workingDirectory: '$(Build.SourcesDirectory)$(projPath)'
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: python
