trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OMF_API/CSharp'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/OMF_API/CSharp'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/OMF_API/CSharp/OMF_API/'
  - name: testPath
    value: '/basic_samples/OMF_API/CSharp/OMF_APITests'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.omf_api_dotnet.ocs.json
  - name: CredFileLibraryOP
    value: product-readiness.omf_api_dotnet.onprem.json
  - name: covStream
    value: OMF_APIDotNet
  - name: bdProject
    value: OMF_API_DotNet

jobs:
  - job: Tests
    strategy:
      matrix:
        ocs:
          imageName: 'ubuntu-16.04'
        onPrem:
          poolName: '00-OSIManaged-Test'
          poolDemands: 'USERNAME -equals $(buildAgent)'
    pool:
      vmImage: $(imageName)
      name: $(poolName)
      demands: $(poolDemands)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: |
          echo Clean
          call dotnet clean
          echo Restore
          call dotnet restore --ignore-failed-sources
          echo Build
          call dotnet msbuild -p:HIGHENTROPYVA=true
          echo Test
          call dotnet test
          echo Complete
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: dotnet
