variables:
- group: LocalServer

jobs:      
- job: OMF_APIDotNet_BS

  pool:
    name: Hosted VS2017

  steps:
  
    - script: |
        dotnet restore
        dotnet build
      workingDirectory: $(Build.SourcesDirectory)/basic_samples/OMF_API/CSharp/OMF_APITests/
      displayName: 'Build'

    - task: ms-codeanalysis.vss-microsoft-security-code-analysis.build-task-binskim.BinSkim@3
      displayName: 'Run BinSkim '
      inputs:
        AnalyzeTarget: '$(Build.SourcesDirectory)\*.dll;$(Build.SourcesDirectory)\*.exe'
